apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  template:
    metadata:
      labels:
        io.kompose.service: db
    spec:
      containers:
        - name: db
          image: library/postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: saleor
            - name: POSTGRES_USER
              value: saleor
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata  # Use a subdirectory here
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/pgdata
              name: saleor-db
            - mountPath: /docker-entrypoint-initdb.d/replica_user.sql
              name: db-cm1
              subPath: replica_user.sql
      volumes:
        - name: saleor-db
          persistentVolumeClaim:
            claimName: saleor-db
        - configMap:
            name: db-cm1
            items:
              - key: replica_user.sql
                path: replica_user.sql
          name: db-cm1
