apiVersion: v1
kind: PersistentVolume
metadata:
  name: saleor-db
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  hostPath:
    path: /mnt/data
