name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Build Docker images
      run: |
        # Build Docker images
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/saleor-api:latest -f saleor-platform/Dockerfile saleor-platform
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/saleor-dashboard:latest -f saleor-platform/Dockerfile.saleor-dashboard saleor-platform
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/postgres:latest -f saleor-platform/Dockerfile.postgres saleor-platform
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/redis:latest -f saleor-platform/Dockerfile.redis saleor-platform

    - name: Push Docker images
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/saleor-api:latest
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/saleor-dashboard:latest
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/postgres:latest
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/redis:latest

    - name: Deploy to GKE
      uses: google-github-actions/deploy-gke@v1
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
        location: ${{ secrets.GKE_CLUSTER_LOCATION }}
        manifests: |
          kubernetes/deployment-saleor-api.yml
          kubernetes/deployment-saleor-dashboard.yml
          kubernetes/deployment-postgres.yml
          kubernetes/deployment-redis.yml
          kubernetes/service-saleor-api.yml
          kubernetes/service-saleor-dashboard.yml
          kubernetes/service-postgres.yml
          kubernetes/service-redis.yml
          kubernetes/ingress.yml
